### PR TITLE
Modified READ.me

### PR DESCRIPTION
**Pull request by SkyMech66**

### CODE REVIEW

**Comment by unnachi27** [comment]
created a pull request

**Comment by Chector22** [comment]
Pull request

**Comment by chlilly** [comment]
Edited file linux.sh for project4.

**Comment by Dijidabubu** [comment]
Official pull request to merge

**Comment by Xabiere-Designs** [comment]
I updated some text to the linux.sh file.

**Comment by K-Bjella** [comment]
Pull Request

**Comment by karacsre** [comment]
Updated linux.sh file

**Comment by GYOUNGJR01** [comment]
Updated linux.sh file

**Pull request closed without merging**
